name: Verify packages

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

  update-pacman:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    needs: checkout-repository  # Ensures this job runs after checkout-repository
    steps:
    - name: Update Pacman and install base packages
      run: |
        # Update pacman database and install essential tools
        pacman -Syyu --noconfirm
        pacman -S --noconfirm grep sed coreutils

  extract-gpu-packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    needs: update-pacman  # Ensures this job runs after update-pacman
    steps:
    - name: Extract GPU packages from install.sh
      run: |
        # Extract all GPU_PACKAGES values from install.sh
        ALL_GPU_PACKAGES=$(grep -E 'export GPU_PACKAGES="[^"]*"' install.sh | \
                          sed 's/export GPU_PACKAGES="\([^"]*\)"/\1/' | \
                          tr '\n' ' ')
        echo "GPU_PACKAGES=$ALL_GPU_PACKAGES" >> $GITHUB_ENV
        echo "GPU_PACKAGES: $ALL_GPU_PACKAGES"

  validate-main-packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:multilib-devel
    needs: extract-gpu-packages  # Ensures this job runs after extract-gpu-packages
    steps:
    - name: Extract and validate packages
      run: |
        # Array to store failed packages
        declare -a failed_packages
        
        # Function to validate a single package
        validate_package() {
          local package="$1"
          # Skip empty, comments, or argument flags
          if [[ -z "$package" ]] || [[ "$package" == "#"* ]] || [[ "$package" == "-"* ]] || [[ "$package" =~ ^-- ]]; then
            return 0
          fi
          
          if ! pacman -Ss "^${package}$" > /dev/null 2>&1; then
            failed_packages+=("$package")
            echo "❌ Package not found: $package"
          else
            echo "✅ Package exists: $package"
          fi
        }

        # Validate GPU packages if the variable is set
        if [[ -n "$GPU_PACKAGES" ]]; then
          echo "📦 Checking GPU packages: $GPU_PACKAGES"
          for pkg in $GPU_PACKAGES; do
            validate_package "$pkg"
          done
        fi

        # Process each .sh file
        for file in *.sh; do
          if [[ -f "$file" ]]; then
            echo "📄 Checking packages in $file..."
            
            # Read file line by line
            while IFS= read -r line || [[ -n "$line" ]]; do
              # Check if line contains pacman install command
              if [[ "$line" == *"pacman -S --noconfirm"* ]]; then
                # Remove the pacman command and any arguments like --ask N
                cleaned_line=$(echo "$line" | \
                  sed 's/pacman -S --noconfirm//g' | \
                  sed 's/--ask [0-9]*//g' | \
                  sed 's/--needed//g' | \
                  tr '\\' ' ')

                # Process packages on this line
                for pkg in $cleaned_line; do
                  validate_package "$pkg"
                done
                
                # If line ends with \, process continuation lines
                if [[ "$line" =~ \\[[:space:]]*$ ]]; then
                  while IFS= read -r line || [[ -n "$line" ]]; do
                    # Stop if we hit a line that doesn't end with \ and isn't part of package list
                    if [[ ! "$line" =~ \\[[:space:]]*$ ]] && [[ ! "$line" =~ ^[[:space:]]*[a-zA-Z0-9] ]]; then
                      break
                    fi
                    # Clean and process the continuation line
                    cleaned_line=$(echo "$line" | sed 's/\\//g')
                    for pkg in $cleaned_line; do
                      validate_package "$pkg"
                    done
                  done
                fi
              fi
            done < "$file"
          fi
        done
        
        # Print summary
        echo "=== Summary ==="
        if [ ${#failed_packages[@]} -eq 0 ]; then
          echo "✅ All packages validated successfully!"
          exit 0
        else
          echo "❌ Failed packages:"
          printf '%s\n' "${failed_packages[@]}"
          echo "Total failed packages: ${#failed_packages[@]}"
          exit 1
