name: Verify Arch Linux Packages

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  check-packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Update Pacman and Install Base Packages
      run: |
        # Enable multilib repository
        sed -i '/\[multilib\]/,/Include/s/^#//' /etc/pacman.conf

        # Update pacman database and install essential tools
        pacman -Syyu --noconfirm
        pacman -S --noconfirm grep sed coreutils

    - name: Extract and validate packages
      run: |
        # Find all .sh files in root directory
        for file in *.sh; do
          if [ -f "$file" ]; then
            echo "Checking packages in $file..."
            
            # Extract package names from pacman commands
            # Matches packages after "pacman -S --noconfirm \" until the next command
            packages=$(awk '/pacman -S --noconfirm/{p=1;next} /^[a-z]/{p=0} p{if($1!="\\") print $1}' "$file" | 
                      grep -v '^$' | 
                      tr -d '\\')
            
            # Also catch single-line package installations
            single_line_packages=$(grep -E "^pacman -S --noconfirm [^\\]" "$file" | 
                                  sed 's/pacman -S --noconfirm //')
            
            all_packages="$packages $single_line_packages"
            
            # Check each package
            echo "$all_packages" | tr ' ' '\n' | while read -r package; do
              if [ ! -z "$package" ]; then
                if pacman -Ss "^${package}$" > /dev/null 2>&1; then
                  echo "✅ Package exists: $package"
                else
                  echo "❌ Package not found: $package"
                  exit 1
                fi
              fi
            done
          fi
        done